# Generated by Django 4.0.3 on 2022-06-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=10)),
                ('username', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logId', models.TextField(max_length=10)),
                ('timeIn', models.DateTimeField()),
                ('timeOut', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=255)),
                ('brand', models.TextField(max_length=255)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.parkinglog')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.vehicle')),
            ],
        ),
    ]
