# Generated by Django 4.0.3 on 2022-06-17 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglog',
            name='timeIn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinglog',
            name='timeOut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
