# Generated by Django 4.0.3 on 2022-06-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0002_delete_manager_user_name_alter_parkinglog_timein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.parkinglog'),
        ),
    ]
