# Generated by Django 4.0.3 on 2022-06-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0004_remove_vehicle_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.parkinglog'),
        ),
    ]
