# Generated by Django 4.0.3 on 2022-06-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0005_vehicle_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='log',
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.user'),
        ),
    ]
