# Generated by Django 4.0.3 on 2022-06-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0007_manager'),
        ('parkingmanage', '0007_vehicle_color'),
    ]

    operations = [
    ]
