# Generated by Django 4.0.3 on 2022-06-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0008_user_avatar_alter_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
