# Generated by Django 4.0.3 on 2022-06-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0008_merge_0007_manager_0007_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.user'),
        ),
    ]
