# Generated by Django 4.0.3 on 2022-06-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0009_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingmanage.user'),
        ),
    ]
