# Generated by Django 4.0.3 on 2022-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingmanage', '0009_manager_address_manager_name_alter_vehicle_user'),
        ('parkingmanage', '0013_alter_parkinglog_vehicle_alter_vehicle_user'),
    ]

    operations = [
    ]
